name: Load APIs

on:
  workflow_dispatch:  # permite execução manual

jobs:
  run-api:
    runs-on: ubuntu-latest

    env:  # <--- Aqui definimos as variáveis de ambiente com os secrets
      API1_ENV: ${{ secrets.API1_ENV }}
      API1_CRED: ${{ secrets.API1_CRED }}
      API2_ENV: ${{ secrets.API2_ENV }}
      API2_CRED: ${{ secrets.API2_CRED }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Restaurar .env e credenciais
        run: |
          bash restore_all.sh